//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeminarskaREST.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie
    {
        public int MovieID { get; set; }
        public string MovieTitle { get; set; }
        public string MovieDesc { get; set; }
        public string MovieDate { get; set; }
        public Nullable<double> MovieRating { get; set; }
    }
}
