//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeminarskaREST.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSeries
    {
        public int UserSeriesID { get; set; }
        public int UserID { get; set; }
        public int SeriesID { get; set; }
        public Nullable<int> LastEpisode { get; set; }
    
        public virtual Series Series { get; set; }
        public virtual User User { get; set; }
    }
}
